// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG7FsMyaXCjL66TYouihJbl-lGT-AvP14',
    appId: '1:165573874763:web:4601d2d02ad01d84d2a9ce',
    messagingSenderId: '165573874763',
    projectId: 'chat-app-firebase-c4dc6',
    authDomain: 'chat-app-firebase-c4dc6.firebaseapp.com',
    storageBucket: 'chat-app-firebase-c4dc6.appspot.com',
    measurementId: 'G-367356G219',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx71nIsGVmxAhHMmONrLvWRGQg1MBWR3c',
    appId: '1:165573874763:android:db204320548ddbdad2a9ce',
    messagingSenderId: '165573874763',
    projectId: 'chat-app-firebase-c4dc6',
    storageBucket: 'chat-app-firebase-c4dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlTXtVVRyku-6n7GHXDh62prnKxwnhB5Y',
    appId: '1:165573874763:ios:8b619d602f5ddfd5d2a9ce',
    messagingSenderId: '165573874763',
    projectId: 'chat-app-firebase-c4dc6',
    storageBucket: 'chat-app-firebase-c4dc6.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlTXtVVRyku-6n7GHXDh62prnKxwnhB5Y',
    appId: '1:165573874763:ios:3246bf1cc0e6b575d2a9ce',
    messagingSenderId: '165573874763',
    projectId: 'chat-app-firebase-c4dc6',
    storageBucket: 'chat-app-firebase-c4dc6.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase.RunnerTests',
  );
}
